
package com.wms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WMS", targetNamespace = "http://service.com", wsdlLocation = "http://182.254.227.113:8080/WMSServicePortForNWN/services/WMS?wsdl")
public class WMS
    extends Service
{

    private final static URL WMS_WSDL_LOCATION;
    private final static WebServiceException WMS_EXCEPTION;
    private final static QName WMS_QNAME = new QName("http://service.com", "WMS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://182.254.227.113:8080/WMSServicePortForNWN/services/WMS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMS_WSDL_LOCATION = url;
        WMS_EXCEPTION = e;
    }

    public WMS() {
        super(__getWsdlLocation(), WMS_QNAME);
    }

    public WMS(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMS_QNAME, features);
    }

    public WMS(URL wsdlLocation) {
        super(wsdlLocation, WMS_QNAME);
    }

    public WMS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMS_QNAME, features);
    }

    public WMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WMS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WMSPortType
     */
    @WebEndpoint(name = "WMSHttpSoap11Endpoint")
    public WMSPortType getWMSHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.com", "WMSHttpSoap11Endpoint"), WMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WMSPortType
     */
    @WebEndpoint(name = "WMSHttpSoap11Endpoint")
    public WMSPortType getWMSHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.com", "WMSHttpSoap11Endpoint"), WMSPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns WMSPortType
     */
    @WebEndpoint(name = "WMSHttpSoap12Endpoint")
    public WMSPortType getWMSHttpSoap12Endpoint() {
        return super.getPort(new QName("http://service.com", "WMSHttpSoap12Endpoint"), WMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WMSPortType
     */
    @WebEndpoint(name = "WMSHttpSoap12Endpoint")
    public WMSPortType getWMSHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.com", "WMSHttpSoap12Endpoint"), WMSPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns WMSPortType
     */
    @WebEndpoint(name = "WMSHttpEndpoint")
    public WMSPortType getWMSHttpEndpoint() {
        return super.getPort(new QName("http://service.com", "WMSHttpEndpoint"), WMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WMSPortType
     */
    @WebEndpoint(name = "WMSHttpEndpoint")
    public WMSPortType getWMSHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.com", "WMSHttpEndpoint"), WMSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMS_EXCEPTION!= null) {
            throw WMS_EXCEPTION;
        }
        return WMS_WSDL_LOCATION;
    }

}
